import React, { useState, useEffect, useRef } from "react";
import * as pdfjsLib from "pdfjs-dist/build/pdf";
import "pdfjs-dist/build/pdf.worker.entry";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import { saveAs } from "file-saver";
import './pdfchatbot.css'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 12, fontFamily: "Helvetica" },
  header: { fontSize: 22, fontWeight: "bold", textAlign: "center", marginBottom: 5 },
  subHeader: { fontSize: 14, marginBottom: 20, textAlign: "center" },
  paperInfo: { fontSize: 12, marginBottom: 15, textAlign: "center", fontStyle: "italic" },
  chapterTitle: {
    fontSize: 14,
    marginBottom: 6,
    marginTop: 16,
    textDecoration: "underline",
    fontWeight: "bold",
  },
  question: { marginBottom: 8, paddingLeft: 12, textAlign: "justify" },
  footer: { marginTop: 30, fontStyle: "italic", fontSize: 10, textAlign: "center" },
});

const ExamPaperDocument = ({ school, subject, questionsByChapter }) => (
  <Document>
    <Page style={styles.page}>
      <Text style={styles.header}>{school}</Text>
      <Text style={styles.subHeader}>{subject} – Final Examination</Text>
      <Text style={styles.paperInfo}>
        Time: 3 Hours | Max Marks: 80 | Answer all questions carefully.
      </Text>
      {questionsByChapter.map(({ chapter, questions }, idx) => (
        <View key={idx}>
          <Text style={styles.chapterTitle}>Chapter {idx + 1}: {chapter}</Text>
          {questions.map((q, i) => (
            <Text key={i} style={styles.question}>
              {i + 1}. {q}
            </Text>
          ))}
        </View>
      ))}
      <Text style={styles.footer}>Generated by Sonar Pro PDF Chatbot</Text>
    </Page>
  </Document>
);

export default function PdfChatBot() {
  const [pdfText, setPdfText] = useState("");
  const [chat, setChat] = useState([]);
  const [messages, setMessages] = useState([
    {
      role: "system",
      content:
        "You are Sonar Pro, a smart assistant. Use the uploaded PDF to answer questions. When the user says 'set paper', generate 3 chapters with 5 unique, concept-based exam questions each from the PDF content.",
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [schoolName, setSchoolName] = useState("Greenfield Public School");
  const [subjectName, setSubjectName] = useState("CBSE 10th Science");
  const [questionsByChapter, setQuestionsByChapter] = useState([]);
  const chatContainerRef = useRef(null);

  useEffect(() => {
    if (chatContainerRef.current)
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
  }, [chat]);

  const cleanText = (text) =>
    text.replace(/\*\*/g, "").replace(/[`~_>#+\-={}\[\]\\]/g, "").trim();

  const handlePdfUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async () => {
      try {
        const typedArray = new Uint8Array(reader.result);
        const pdf = await pdfjsLib.getDocument(typedArray).promise;
        let text = "";
        for (let i = 1; i <= pdf.numPages; i++) {
          const page = await pdf.getPage(i);
          const content = await page.getTextContent();
          text += content.items.map((item) => item.str).join(" ") + "\n";
        }
        setPdfText(cleanText(text));
        alert("✅ PDF uploaded and processed successfully!");
      } catch {
        alert("❌ Failed to extract PDF text.");
      }
    };
    reader.readAsArrayBuffer(file);
  };

  const handleSend = async () => {
    if (!input.trim()) return;
    const userMsg = { role: "user", content: input };
    setChat((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    const updatedMessages = [
      ...messages,
      ...chat,
      { role: "user", content: `PDF Content: ${pdfText}\nQuestion: ${input}` },
    ];

    try {
      const response = await fetch("https://api.perplexity.ai/chat/completions", {
        method: "POST",
        headers: {
          Authorization: "Bearer pplx-YOUR_API_KEY",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "sonar-pro",
          messages: updatedMessages,
          temperature: 0.7,
          max_tokens: 1000,
        }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error?.message || "API error");
      const reply = cleanText(data.choices?.[0]?.message?.content || "No reply");
      setChat((prev) => [...prev, { role: "assistant", content: reply }]);

      if (/set paper|generate exam/i.test(input)) {
        await generateExamPaper();
      }
    } catch (err) {
      setChat((prev) => [...prev, { role: "assistant", content: "❌ " + err.message }]);
    } finally {
      setLoading(false);
    }
  };

  const generateExamPaper = async () => {
    if (!pdfText) return alert("Upload a PDF first!");
    setLoading(true);
    try {
      const response = await fetch("https://api.perplexity.ai/chat/completions", {
        method: "POST",
        headers: {
          Authorization: "Bearer pplx-YOUR_API_KEY",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "sonar-pro",
          messages: [
            {
              role: "user",
              content: `Based on this PDF content:\n${pdfText}\n\nGenerate 3 chapters. For each chapter, give 5 unique exam-style questions relevant to the material. Return JSON in this format:\n[{ "chapter": "Chapter name", "questions": ["Q1", "Q2", "Q3", "Q4", "Q5"] }]`,
            },
          ],
          temperature: 0.7,
          max_tokens: 1500,
        }),
      });

      const data = await response.json();
      const raw = data.choices?.[0]?.message?.content || "[]";
      const parsed = JSON.parse(raw.match(/\[.*\]/s)?.[0] || "[]");
      setQuestionsByChapter(parsed);

      setChat((prev) => [
        ...prev,
        { role: "assistant", content: "📘 Exam paper generated! Click below to download." },
      ]);
    } catch {
      alert("❌ Failed to generate exam paper automatically.");
    } finally {
      setLoading(false);
    }
  };

  const downloadExamPaper = async () => {
    if (!questionsByChapter.length) return alert("No paper generated yet!");
    const doc = (
      <ExamPaperDocument
        school={schoolName}
        subject={subjectName}
        questionsByChapter={questionsByChapter}
      />
    );
    const blob = await (await pdf(doc)).toBlob();
    saveAs(blob, `${schoolName.replace(/\s+/g, "_")}_${subjectName}_Exam_Paper.pdf`);
  };

  return (
    <div className="chatbot-container">
      <h2 className="chatbot-title">🎓 Sonar Pro PDF Chatbot & Exam Paper Creator</h2>

      <div className="upload-section">
        <label className="upload-label">
          Upload Study PDF:
          <input type="file" accept="application/pdf" onChange={handlePdfUpload} />
        </label>
      </div>

      <div ref={chatContainerRef} className="chat-box">
        {chat.length === 0 ? (
          <div className="chat-placeholder">Chat will appear here...</div>
        ) : (
          chat.map((msg, i) => (
            <div key={i} className={`chat-message ${msg.role}`}>
              <b>{msg.role === "user" ? "You: " : "Sonar: "}</b> {msg.content}
            </div>
          ))
        )}
        {loading && <div className="loading-message">⏳ Thinking...</div>}
      </div>

      <div className="input-section">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask about the PDF or type 'set paper'..."
          onKeyDown={(e) => e.key === "Enter" && handleSend()}
        />
        <button
          onClick={handleSend}
          className={`send-btn ${loading || !pdfText ? "disabled" : ""}`}
          disabled={loading || !pdfText}
        >
          Send
        </button>
      </div>

      {questionsByChapter.length > 0 && (
        <div className="download-section">
          <h4>📄 Your Exam Paper is Ready</h4>
          <button onClick={downloadExamPaper} className="download-btn">
            Download PDF Exam Paper
          </button>
        </div>
      )}
    </div>
  );
}
